;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cider-eval-defun-at-point
        cljr-slash
        clojure-align
        counsel-M-x
        counsel-yank-pop
        default-indent-new-line
        downcase-region
        electric-newline-and-maybe-indent
        indent-for-tab-command
        indent-new-comment-line
        js2-line-break
        kill-region
        markdown-cycle
        markdown-electric-backquote
        markdown-outdent-or-delete
        org-ctrl-c-ctrl-c
        org-cycle
        org-end-of-line
        org-metaleft
        org-metaright
        org-self-insert-command
        org-shiftright
        org-yank
        rjsx-delete-creates-full-tag
        slime-autodoc-space
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-previous-sexp
        sp-unwrap-sexp
        upcase-region
        wdired-finish-edit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-projectile-ag
        ignore
        ivy-switch-buffer
        ))
