(progn
  (require 'my-packages)
  (require 'better-defaults)
  (require 'my-evil)
  (require 'my-theme)
  (require 'my-mode-line)
  (require 'my-ivy)
  (require 'my-projectile)
  (require 'my-magit)
  (require 'my-company)
  (require 'my-python)
  (require 'my-clojure)
  (require 'my-nlinum)
  (require 'my-ace-window)
)

(provide 'settings)
