(progn
  (require 'setup-packages)
  (require 'better-defaults)
  (require 'setup-programing)
  (require 'setup-evil)
  (require 'setup-theme)
  (require 'setup-editorconfig)
  (require 'setup-mode-line)
  (require 'setup-ivy)
  (require 'setup-projectile)
  (require 'setup-magit)
  (require 'setup-company)
  (require 'setup-python)
  (require 'setup-clojure)
  (require 'setup-js)
  (require 'setup-cl)
  (require 'setup-scheme)
  ;; (require 'setup-nlinum)
  (require 'setup-ace-window)
  (require 'setup-which-key))

(provide 'settings)
